Web/ZENBEAR.Web/Controllers/IssuesController.cs
namespace ZENBEAR.Web.Controllers
{
    using System.Threading.Tasks;

    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;
    using ZENBEAR.Common;
    using ZENBEAR.Services.Data;
    using ZENBEAR.Web.ViewModels.Issues;

    public class IssuesController : Controller
    {
        private readonly IIssuesService issuesService;
        private readonly IProjectsService projectsService;

        public IssuesController(IIssuesService issuesService, IProjectsService projectsService)
        {
            this.issuesService = issuesService;
            this.projectsService = projectsService;
        }

        [HttpGet]
        [Authorize(Roles = GlobalConstants.AdministratorRoleName)]
        public IActionResult Create()
        {
            var viewModel = new CreateIssueInputModel
            {
                Projects = this.projectsService.GetAllProjectsNames(),
            };

            return this.View(viewModel);
        }

        [HttpPost]
        [Authorize(Roles = GlobalConstants.AdministratorRoleName)]
        public async Task<IActionResult> Create(CreateIssueInputModel input)
        {
            if (!this.ModelState.IsValid)
            {
                return this.View(input);
            }

            await this.issuesService.CreateAsync(input);

            this.TempData["Message"] = $"{input.Name} Issue added successfully.";

            return this.RedirectToAction("Index", "Home");
        }
    }
}

Web/ZENBEAR.Web/Controllers/JobtitlesController.cs
namespace ZENBEAR.Web.Controllers
{
    using System.Threading.Tasks;

    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;
    using ZENBEAR.Common;
    using ZENBEAR.Services.Data;
    using ZENBEAR.Web.ViewModels.Jobtitles;

    public class JobtitlesController : Controller
    {
        private readonly IDepartmentsService departmentsService;
        private readonly IJobtitleService jobtitleService;

        public JobtitlesController(IDepartmentsService departmentsService, IJobtitleService jobtitleService)
        {
            this.departmentsService = departmentsService;
            this.jobtitleService = jobtitleService;
        }

        [HttpGet]
        [Authorize(Roles = GlobalConstants.AdministratorRoleName)]
        public IActionResult Create()
        {
            var viewModel = new CreateJobtitleInputModel
            {
                Departments = this.departmentsService.GetAllDepNames(),
            };

            return this.View(viewModel);
        }

        [HttpPost]
        [Authorize(Roles = GlobalConstants.AdministratorRoleName)]
        public async Task<IActionResult> CreateAsync(CreateJobtitleInputModel input)
        {
            if (!this.ModelState.IsValid)
            {
                return this.View(input);
            }

            await this.jobtitleService.CreateAsync(input);

            this.TempData["Message"] = $"Jobtitle {input.Name} added successfully.";

            return this.RedirectToAction("All", "Departments");
        }

        [HttpGet]
        [Authorize(Roles = GlobalConstants.AdministratorRoleName)]
        public IActionResult Edit(int id)
        {
            var viewModel = this.jobtitleService.JobtitleById(id);

            if (viewModel.Name == null)
            {
                return this.BadRequest();
            }

            return this.View(viewModel);
        }

        [HttpPost]
        [Authorize(Roles = GlobalConstants.AdministratorRoleName)]
        public async Task<IActionResult> Edit(int id, EditJobtitleViewModel input)
        {
            if (!this.ModelState.IsValid)
            {
                return this.View(input);
            }

            await this.jobtitleService.UpdateAsync(id, input);

            this.TempData["Message"] = $"Jobtitle Name changed to {input.Name}!";

            return this.RedirectToAction("All", "Departments");
        }

        [Authorize(Roles = GlobalConstants.AdministratorRoleName)]
        public async Task<IActionResult> Delete(int id)
        {
            var success = await this.jobtitleService.DeleteByIdAsync(id);

            if (success == false)
            {
                return this.RedirectToAction("Error", "Home");
            }

            return this.RedirectToAction("All", "Departments");
        }
    }
}

Web/ZENBEAR.Web/Controllers/ProjectsController.cs
namespace ZENBEAR.Web.Controllers
{
    using System.Threading.Tasks;

    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;
    using ZENBEAR.Common;
    using ZENBEAR.Services.Data;
    using ZENBEAR.Web.ViewModels.Projects;

    public class ProjectsController : Controller
    {
        private readonly IProjectsService projectsService;
        private readonly IDepartmentsService departmentsService;

        public ProjectsController(IProjectsService projectsService, IDepartmentsService departmentsService)
        {
            this.projectsService = projectsService;
            this.departmentsService = departmentsService;
        }

        [HttpGet]
        [Authorize(Roles = GlobalConstants.AdministratorRoleName)]
        public IActionResult Create()
        {
            var viewModel = new CreateProjectInputModel
            {
                Departments = this.departmentsService.GetAllDepNames(),
            };

            return this.View(viewModel);
        }

        [HttpPost]
        [Authorize(Roles = GlobalConstants.AdministratorRoleName)]
        public async Task<IActionResult> Create(CreateProjectInputModel input)
        {
            if (!this.ModelState.IsValid)
            {
                return this.View(input);
            }

            await this.projectsService.CreateAsync(input);

            this.TempData["Message"] = $"{input.Name} Project added successfully.";

            return this.RedirectToAction("Index", "Home");
        }
    }
}

Web/ZENBEAR.Web/Controllers/RolesController.cs
namespace ZENBEAR.Web.Controllers
{
    using System.Linq;
    using System.Threading.Tasks;

    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;
    using ZENBEAR.Common;
    using ZENBEAR.Data.Models;
    using ZENBEAR.Services.Data;
    using ZENBEAR.Web.ViewModels.Roles;

    public class RolesController : Controller
    {
        private readonly RoleManager<ApplicationRole> roleManager;
        private readonly IRoleService roleService;

        public RolesController(IRoleService roleService, RoleManager<ApplicationRole> roleManager)
        {
            this.roleService = roleService;
            this.roleManager = roleManager;
        }

        [Authorize(Roles = GlobalConstants.AdministratorRoleName)]
        public IActionResult All()
        {
            var roles = this.roleManager.Roles.ToList();
            return this.View(roles);
        }

        [HttpGet]
        [Authorize(Roles = GlobalConstants.AdministratorRoleName)]
        public IActionResult Create()
        {
            return this.View();
        }

        [HttpPost]
        [Authorize(Roles = GlobalConstants.AdministratorRoleName)]
        public async Task<IActionResult> CreateAsync(CreateRoleInputModel input)
        {
            if (!this.ModelState.IsValid)
            {
                return this.View(input);
            }

            await this.roleService.CreateAsync(input);

            this.TempData["Message"] = $"{input.Name} Role added successfully.";

            return this.RedirectToAction("Index", "Home");
        }
    }
}

Web/ZENBEAR.Web/Views/Shared/_Layout.cshtml
@using ZENBEAR.Common
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@this.ViewData["Title"] - @GlobalConstants.SystemName</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">

    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/baseLayout.css" asp-append-version="true" />
    <link rel="shortcut icon" type="image/x-icon" href="~/favicon.ico" />
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                        <img src="https://static1.squarespace.com/static/5ef66d7f1de9065ae3cd8f2e/t/60b776e8297d2d2c20e289d5/1622648836361/" width="90" height="40"
                             class="me-3"
                             alt="MDB Logo"
                             loading="lazy" />
                        <small></small>
                    </a>

                    <ul class="nav justify-content-center">

                        @if (User.Identity.IsAuthenticated)
                        {
                    @if (User.IsInRole(GlobalConstants.ITRole) || User.IsInRole(GlobalConstants.InfoSecRole))
                    {
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Tickets" asp-action="Open">&#128452; Manage Tickets</a>
                    </li>                }
                                    @if (User.IsInRole(GlobalConstants.AdministratorRoleName))
                                    {
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Tickets" asp-action="AllTickets">&#128452; All Tickets</a>
                    </li>                }


                                                    <li class="nav-item">
                                                        <a class="nav-link text-dark" asp-area="" asp-controller="Tickets" asp-action="MyTickets">&#128451; MyTickets</a>
                                                    </li>
                                                                    <li class="nav-item">
                                                                        <a class="nav-link text-dark" asp-area="" asp-controller="Tickets" asp-action="Create">&#128395; Create Ticket</a>
                                                                    </li>
                                                                                    <li class="nav-item">
                                                                                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">&#128477; Privacy</a>
                                                                                    </li>

                                                                                                    @if (User.IsInRole(GlobalConstants.AdministratorRoleName))
                                                                                                    {
                                                                                    <li class="nav-item dropdown">
                                                                                        <a class="nav-link dropdown-toggle text-dark" href="" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                                                                            &#128218; Manage
                                                                                        </a>
                                                                                        <ul class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
                                                                                            <li><a class="nav-link text-dark" asp-area="" asp-controller="Users" asp-action="All">Users</a></li>
                                                                                            <li><a class="nav-link text-dark" asp-area="" asp-controller="Departments" asp-action="All">Departments</a></li>
                                                                                        </ul>
                                                                                    </li>
                                                                                                        <li class="nav-item dropdown">
                                                                                                            <a class="nav-link dropdown-toggle text-dark" href="" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                                                                                                &#10133; Add
                                                                                                            </a>
                                                                                                            <ul class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
                                                                                                                <li><a class="nav-link text-dark" asp-area="" asp-controller="Users" asp-action="Create">User</a></li>
                                                                                                                <li><a class="nav-link text-dark" asp-area="" asp-controller="Roles" asp-action="Create">Role</a></li>
                                                                                                                <li><a class="nav-link text-dark" asp-area="" asp-controller="Issues" asp-action="Create">Issue</a></li>
                                                                                                                <li><a class="nav-link text-dark" asp-area="" asp-controller="Projects" asp-action="Create">Project</a></li>
                                                                                                                <li><a class="nav-link text-dark" asp-area="" asp-controller="Jobtitles" asp-action="Create">Jobtitle</a></li>
                                                                                                                <li><a class="nav-link text-dark" asp-area="" asp-controller="Departments" asp-action="Create">Department</a></li>
                                                                                                            </ul>
                                                                                                        </li>
                                                                                                                            <li class="nav-item">
                                                                                                                                <a class="nav-link text-dark" asp-area="Statistics" asp-controller="Reports" asp-action="TicketsMonthReport">&#128202; Report</a>
                                                                                                                            </li>}

                                                                                                                    @if (User.IsInRole(GlobalConstants.ITRole) || User.IsInRole(GlobalConstants.InfoSecRole))
                                                                                                                    {
                                                                                                    <li class="nav-item">
                                                                                                        <a class="nav-link text-dark" asp-area="Statistics" asp-controller="Reports" asp-action="IssuesTypeReport">&#128202; Report</a>
                                                                                                    </li>}}
                    </ul>

                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>

    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @this.RenderBody()
        </main>
    </div>

    <footer id="footer" class="bg-light text-center text-lg-start">
        <!-- Copyright -->
        <div class="text-center p-2">
            © 2022 Copyright:
            <a class="text-dark" href="">ZenBear.com</a>
        </div>
        <!-- Copyright -->
    </footer>

    <script src="https://kit.fontawesome.com/a199d1b466.js" crossorigin="anonymous"></script>
    <script src="~/lib/jquery/dist/jquery.min.js" asp-append-version="true"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js" asp-append-version="true"></script>
    <script src="~/lib/jquery-validation-unobtrusive/dist/jquery.validate.unobtrusive.min.js" asp-append-version="true"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.min.js" asp-append-version="true"></script>
    <script src="~/js/site.min.js" asp-append-version="true"></script>
    @await this.RenderSectionAsync("Scripts", required: false)
</body>
</html>

Web/ZENBEAR.Web/Views/Shared/_PagingPartial.cshtml
@model ZENBEAR.Web.ViewModels.Paging.PagingViewModel

<nav aria-label="...">
    <ul class="pagination justify-content-center">
        <li class="page-item @if (!Model.HasPreviousPage) { <text>disabled</text> }">
            <a class="page-link" asp-action="All" asp-route-id="@Model.PreviousPageNumber">Previous</a>
        </li>
        @for (int i = Model.PageNumber - 2; i < Model.PageNumber; i++)
        {
            if (i > 0)
            {
                <li class="page-item"><a class="page-link" asp-action="All" asp-route-id="@i">@i</a></li>
            }
        }
        <li class="page-item active" aria-current="page">
            <span class="page-link">
                @Model.PageNumber
                <span class="sr-only">(current)</span>
            </span>
        </li>
        @for (int i = Model.PageNumber + 1; i <= Model.PageNumber + 2; i++)
        {
            if (i <= Model.PagesCount)
            {
                <li class="page-item"><a class="page-link" asp-action="All" asp-route-id="@i">@i</a></li>
            }
        }
        <li class="page-item @if (!Model.HasNextPage) { <text>disabled</text> }">
            <a class="page-link" asp-action="All" asp-route-id="@Model.NextPageNumber">Next</a>
        </li>
    </ul>
</nav>