Web/ZENBEAR.Web/Controllers/CommentsController.cs
namespace ZENBEAR.Web.Controllers
{
    using System.Threading.Tasks;

    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;
    using ZENBEAR.Data.Models;
    using ZENBEAR.Services.Data;

    public class CommentsController : Controller
    {
        private readonly ICommentsService commentsService;
        private readonly ITicketsService ticketsService;
        private readonly UserManager<ApplicationUser> userManager;

        public CommentsController(
            ICommentsService commentsService,
            UserManager<ApplicationUser> userManager,
            ITicketsService ticketsService)
        {
            this.commentsService = commentsService;
            this.ticketsService = ticketsService;
            this.userManager = userManager;
        }

        [HttpPost]
        [Authorize]
        public async Task<IActionResult> Comment(string content, int ticketId)
        {
            var user = await this.userManager.GetUserAsync(this.User);
            var ticket = this.ticketsService.GetTicketById(ticketId);

            await this.commentsService.CreateAsync(content, user.Id, ticketId);

            if (user.Id != ticket.ReporterId)
            {
                return this.RedirectToAction("Details", "Tickets", new { @id = ticketId });
            }

            return this.RedirectToAction("MyTicketsDetails", "Tickets", new { @id = ticketId });
        }
    }
}

Web/ZENBEAR.Web/Controllers/TicketsController.cs
namespace ZENBEAR.Web.Controllers
{
    using System.Text;
    using System.Threading.Tasks;

    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Hosting;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;
    using ZENBEAR.Common;
    using ZENBEAR.Data.Models;
    using ZENBEAR.Services.Data;
    using ZENBEAR.Services.Messaging;
    using ZENBEAR.Web.ViewModels.Tickets;

    public class TicketsController : Controller
    {
        private readonly IProjectsService projectsService;
        private readonly ITicketsService ticketsService;
        private readonly IDepartmentsService departmentsService;
        private readonly UserManager<ApplicationUser> userManager;
        private readonly IWebHostEnvironment environment;
        private readonly IEmailSender emailSender;

        public TicketsController(
            IProjectsService projectsService,
            ITicketsService ticketsService,
            IDepartmentsService departmentsService,
            UserManager<ApplicationUser> userManager,
            IWebHostEnvironment environment,
            IEmailSender emailSender)
        {
            this.projectsService = projectsService;
            this.ticketsService = ticketsService;
            this.departmentsService = departmentsService;
            this.userManager = userManager;
            this.environment = environment;
            this.emailSender = emailSender;
        }

        [HttpGet]
        [Authorize(Roles = GlobalConstants.AdministratorRoleName)]
        public IActionResult AllTickets(int id = 1)
        {
            if (id <= 0)
            {
                return this.NotFound();
            }

            var viewModel = new AllTicketsAdminViewModel
            {
                AllTickets = this.ticketsService.GetAllTickets(GlobalConstants.ItemsPerPage, id),
                ItemsPerPage = GlobalConstants.ItemsPerPage,
                PageNumber = id,
                ItemsCount = this.ticketsService.GetCount(),
            };

            return this.View(viewModel);
        }

        [HttpGet]
        [Authorize(Roles = GlobalConstants.ITorInfoSec)]
        public async Task<IActionResult> OpenAsync(int id = 1)
        {
            if (id <= 0)
            {
                return this.NotFound();
            }

            var user = await this.userManager.GetUserAsync(this.User);
            var project = this.projectsService.GetProjectByDepartmentId(user.DepartmentId);

            var viewModel = new ListOpenTicketsViewModel
            {
                OpenTickets = this.ticketsService.GetOpenTickets(project, GlobalConstants.ItemsPerPage, id),
                ItemsPerPage = GlobalConstants.ItemsPerPage,
                PageNumber = id,
                ItemsCount = this.ticketsService.GetOpenTicketsCount(),
            };

            return this.View(viewModel);
        }

        [HttpGet]
        [Authorize]
        public async Task<IActionResult> MyTickets(int id = 1)
        {
            if (id <= 0)
            {
                return this.NotFound();
            }

            var user = await this.userManager.GetUserAsync(this.User);

            var viewModel = new AllMyTicketsViewModel
            {
                ItemsPerPage = GlobalConstants.ItemsPerPage,
                PageNumber = id,
                MyTickets = this.ticketsService.GetUserTickets(user.Id, GlobalConstants.ItemsPerPage, id),
                ItemsCount = this.ticketsService.GetUserTicketsCount(user.Id),
            };

            return this.View(viewModel);
        }

        [HttpGet]
        [Authorize(Roles = GlobalConstants.ITorInfoSec)]
        public async Task<IActionResult> ClosedAsync(int id = 1)
        {
            if (id <= 0)
            {
                return this.NotFound();
            }

            var user = await this.userManager.GetUserAsync(this.User);
            var project = this.projectsService.GetProjectByDepartmentId(user.DepartmentId);

            var viewModel = new ListClosedTicketsViewModel
            {
                ListClosedTickets = this.ticketsService.GetClosedTickets(project, GlobalConstants.ItemsPerPage, id),
                ItemsPerPage = GlobalConstants.ItemsPerPage,
                PageNumber = id,
                ItemsCount = this.ticketsService.GetClosedTicketsCount(),
            };

            return this.View(viewModel);
        }

        [HttpGet]
        [Authorize(Roles = GlobalConstants.ITorInfoSec + "," + GlobalConstants.AdministratorRoleName)]
        public async Task<IActionResult> SearchAsync(string search)
        {
            bool parsed = int.TryParse(search, out int id);
            var viewModel = new SearchedTicketViewModel();

            if (parsed)
            {
                var user = await this.userManager.GetUserAsync(this.User);
                var project = this.projectsService.GetProjectByDepartmentId(user.DepartmentId);

                viewModel = this.ticketsService.GetSearchedTicket(id, project);
            }
            else
            {
                viewModel = null;
            }

            return this.View(viewModel);
        }

        [HttpGet]
        [Authorize(Roles = GlobalConstants.ITorInfoSec + "," + GlobalConstants.AdministratorRoleName)]
        public async Task<IActionResult> DetailsAsync(int id)
        {
            var user = await this.userManager.GetUserAsync(this.User);
            var department = this.departmentsService.GetDepartmentById(user.DepartmentId);

            var viewModel = new AllTicketDetailsViewModel
            {
                Ticket = this.ticketsService.GetTicketDetailById(id),
                ListItems = this.ticketsService.GetAllProjectEmployees(department.Name),
            };

            if (viewModel == null)
            {
                return this.BadRequest();
            }

            return this.View(viewModel);
        }

        [HttpGet]
        [Authorize]
        public IActionResult MyTicketsDetails(int id)
        {
            var viewModel = new MyTicketDetailsViewModel
            {
                Ticket = this.ticketsService.GetTicketDetailById(id),
            };

            if (viewModel == null)
            {
                return this.BadRequest();
            }

            return this.View(viewModel);
        }

        [HttpPost]
        [Authorize(Roles = GlobalConstants.ITorInfoSec)]
        public async Task<IActionResult> Assignee(int ticketId, string assigneeId)
        {
            await this.ticketsService.AssigneeUserToTicketAsync(ticketId, assigneeId);

            return this.RedirectToAction("Details", "Tickets", new { @id = ticketId });
        }

        [HttpGet]
        [Authorize]
        public IActionResult Create()
        {
            var viewModel = new CreateTicketinputModel
            {
                ListItems = this.projectsService.LoadProjectsItems(),
            };

            return this.View(viewModel);
        }

        [HttpPost]
        [Authorize]
        public async Task<IActionResult> Create(CreateTicketinputModel input)
        {
            if (!this.ModelState.IsValid)
            {
                input.ListItems = this.projectsService.LoadProjectsItems();
                return this.View(input);
            }

            var user = await this.userManager.GetUserAsync(this.User);

            await this.ticketsService.CreateAsync(input, user.Id, $"{this.environment.WebRootPath}/attachments");

            this.TempData["Message"] = "Your request is successfully send ";

            return await this.SendEmail(input);
        }

        [HttpPost]
        [Authorize(Roles = GlobalConstants.ITorInfoSec + "," + GlobalConstants.AdministratorRoleName)]
        public async Task<IActionResult> Resolve(int ticketId)
        {
            await this.ticketsService.ResolveTicketAsync(ticketId);

            return this.Redirect("Open");
        }

        [HttpPost]
        public async Task<IActionResult> SendEmail(CreateTicketinputModel ticket)
        {
            var email = ticket.Project == GlobalConstants.ITProject ? "gready000@gmail.com" : "gready000@abv.bg";
            var subject = ticket.Summary;
            var message = $"Hello, you have new {ticket.Project} request with {ticket.Priority} priority. See it in open tickets. Have a nice day!";

            var html = new StringBuilder();
            html.AppendLine($"<h1>{subject}</h1>");
            html.AppendLine($"<h3>{message}</h3>");

            await this.emailSender.SendEmailAsync("gready000@students.softuni.bg", "ZenBear", email, subject, html.ToString());

            return this.Redirect("MyTickets");
        }
    }
}

Web/ZENBEAR.Web/Views/Tickets/AllTickets.cshtml
@model ZENBEAR.Web.ViewModels.Tickets.AllTicketsAdminViewModel
@using ZENBEAR.Data.Models.Enums

<script src="https://kit.fontawesome.com/a199d1b466.js" crossorigin="anonymous"></script>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
<link rel="stylesheet" href="~/css/allticketstable.css" asp-append-version="true" />
<link rel="stylesheet" href="~/css/rate.css" asp-append-version="true" />
<link rel="stylesheet" href="~/css/rate.css" asp-append-version="true" />

@{
    this.ViewData["Title"] = "All Tickets";
}

<div class="row">
    <div id="admin" class="col s12">
        <div class="card material-table">
            <div class="table-header">
                <span class="table-title">@this.ViewData["Title"]</span>
                <div class="actions">
                </div>
            </div>
            <table id="datatable">
                <thead>
                    <tr>
                        <th>Issue Type</th>
                        <th>Key</th>
                        <th>Summary</th>
                        <th>Reporter</th>
                        <th>Create On</th>
                        <th>Assignee</th>
                        <th>Status</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var ticket in Model.AllTickets)
                    {
                        <tr id="li" onclick="location.href = '@(Url.Action("MyTicketsDetails", "Tickets", new { Id = ticket.Id }))'">
                            <td style="width: 5%; ">@ticket.IssueType</td>
                            <td style="width: 5%; ">TI-@ticket.Id</td>
                            <td style="max-width: 150px; width: 30%">@ticket.Summary</td>
                            <td style="width: 20%">@ticket.Reporter</td>
                            <td style="width: 12%">@ticket.CreateOn</td>
                            <td style="width: 20%">@ticket.Assignee</td>
                            <td style="width: 10%">
                                @if (ticket.Status == Status.Closed.ToString())
                                {
                                    <div style="padding-left: 13px; color: blue">@ticket.Status</div>
                                }
                                else
                                {
                                    <div style="padding-left: 13px; color: green">@ticket.Status</div>
                                }
                            </td>
                        </tr>
                    }
                </tbody>
            </table>

            <nav aria-label="..." style="margin-left: 10px; margin-top: 5px;">
                <ul class="pagination">
                    <li class="page-item @if (!Model.HasPreviousPage) { <text>disabled</text> }">
                        <a class="page-link" asp-action="Closed" asp-route-id="@Model.PreviousPageNumber">Previous</a>
                    </li>
                    @for (int i = Model.PageNumber - 2; i < Model.PageNumber; i++)
                    {
                        if (i > 0)
                        {
                            <li class="page-item"><a class="page-link" asp-action="Closed" asp-route-id="@i">@i</a></li>
                        }
                    }
                    <li class="page-item active" aria-current="page">
                        <span class="page-link">
                            @Model.PageNumber
                            <span class="sr-only">(current)</span>
                        </span>
                    </li>
                    @for (int i = Model.PageNumber + 1; i <= Model.PageNumber + 2; i++)
                    {
                        if (i <= Model.PagesCount)
                        {
                            <li class="page-item"><a class="page-link" asp-action="Closed" asp-route-id="@i">@i</a></li>
                        }
                    }
                    <li class="page-item @if (!Model.HasNextPage) { <text>disabled</text> }">
                        <a class="page-link" asp-action="Closed" asp-route-id="@Model.NextPageNumber">Next</a>
                    </li>
                </ul>
            </nav>

        </div>
    </div>
</div>

<script src="~/js/allticketstable.js" asp-append-version="true"></script>

Web/ZENBEAR.Web/Views/Tickets/Details.cshtml
@model ZENBEAR.Web.ViewModels.Tickets.AllTicketDetailsViewModel
@using ZENBEAR.Data.Models.Enums

<head>
    <script src="https://kit.fontawesome.com/a199d1b466.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="~/css/finishbutton.css">
    <link rel="stylesheet" href="~/css/comments.css">
    <link rel="stylesheet" href="~/css/ticketsDetails.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta2/css/all.min.css" integrity="sha512-YWzhKL2whUzgiheMoBFwW8CKV4qpHQAEuvilg9FAn5VJUDwKZZxkJNuGM4XkWuk94WCrrwslk8yWNGmY1EduTA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <style>
        body {
            background-image: linear-gradient(135deg, tomato, rebeccapurple);
        }
    </style>
</head>

<body>
    <div id="sides">
        <div class="tab">
            <button id="backBtn" class="buttonLeft" onclick="history.back(-1)">&#8592; Back</button>
            <p id="element">&#9889; @Model.Ticket.IssueType Issue</p>
            <p id="element">&#9806; TI-@Model.Ticket.Id</p>
            @if (Model.Ticket.Status == Status.Open.ToString())
            {
                <form id="resolve" method="post" asp-action="Resolve" asp-route-ticketId="@Model.Ticket.Id">
                    <button type="submit" class="btn btn-success">Resolve Issue</button>
                </form>
            }
        </div>
        <hr />
        <div id="sides">
            <div id="left">
                <i class="fa-light fa-ballot-check"></i>
                <h4 id="element2"><i class="fa-solid fa-envelope-open-text"></i> @Model.Ticket.Summary</h4>
                <p id="element1">Priority</p>
                <p id="element1" style="color:@(Model.Ticket.Priority == Priority.Urgent.ToString() ? "red" : "green");" >&#10071;@Model.Ticket.Priority</p>
                <div id="element2">
                    <p>Attachments</p>
                    @if (Model.Ticket.Attachments != null)
                    {
                        @foreach (var item in Model.Ticket.Attachments)
                        {
                            var fileName = "/attachments/tickets/" + @item.Id + "." + @item.Extension;
                            <i class="fa-solid fa-paperclip"></i><a href="@fileName" download>Download </a>
                        }
                    }
                </div>
                <div id="element2">
                    <i class="fa-regular fa-keyboard"></i>
                    <textarea asp-for="Ticket.Description" class="form-control" rows="7"></textarea>
                    <span asp-validation-for="Ticket.Description" class="text-danger"></span>
                </div>

            </div>

            <div id="right">
                <h4 id="details">&#8505;&#65039; Details</h4>
                <hr />

                <form id="assignee" method="post" asp-action="Assignee" asp-route-ticketId="@Model.Ticket.Id" asp-route-assigneeId="@Model.AssigneeId">
                    <p id="assignee">Assignee</p>
                    <select onChange="this.form.submit()" asp-for="AssigneeId" class="test" asp-items="@Model.ListItems">
                        @if (Model.Ticket.Assignee != null)
                        {
                            <option value="" selected="selected">@Model.Ticket.Assignee</option>
                        }
                        else
                        {
                            <option value="" selected="selected">Unassigned</option>
                        }
                    </select>
                </form>

                <table class="table-fill">
                    <tbody class="table-hover">

                        <tr>
                            <td class="text-left">Reporter</td>
                            <td class="text-left">@Model.Ticket.Reporter.FullName</td>
                        </tr>
                        <tr>
                            <td class="text-left">Telephone</td>
                            @if (Model.Ticket.PhoneNumber != null)
                            {
                                <td class="text-left">@Model.Ticket.PhoneNumber</td>
                            }
                            else
                            {
                                <td class="text-left">None</td>
                            }
                        </tr>
                        <tr>
                            <td class="text-left">Email</td>
                            <td class="text-left">@Model.Ticket.Reporter.Email</td>
                        </tr>
                        <tr>
                            <td class="text-left">Department</td>
                            <td class="text-left">@Model.Ticket.Reporter.Department</td>
                        </tr>
                        <tr>
                            <td class="text-left">Jobtitle</td>
                            <td class="text-left">@Model.Ticket.Reporter.Jobtitle</td>
                        </tr>
                    </tbody>
                </table>
            </div>
            <input type="hidden" asp-for="Ticket.Id" />
            <h5 id="commentHeding">Comments</h5>
            @if (Model.Ticket.Comments != null)
            {
                @foreach (var comment in Model.Ticket.Comments)
                {
                    <div id="comment" class="comments-container">

                        <ul id="comments-list" class="comments-list">
                            <li>
                                <div class="comment-main-level">
                                    <div class="comment-box">
                                        <div class="comment-head">
                                            <h6 class="comment-name by-author">@comment.AddByUser</h6>
                                            <span>@comment.CreatedOn.ToString("dd/MM/yyyy HH:mm")</span>
                                            <i class="fa fa-reply"></i>
                                            <i class="fa fa-heart"></i>
                                        </div>
                                        <div class="comment-content">
                                            @comment.Content
                                        </div>
                                    </div>
                                </div>
                            </li>
                        </ul>
                    </div>
                }
            }
            <div id='buttons'>
                <button id="show" style="margin-left: 38px; margin-top: 20px;" type="button" class="btn btn-info">Press for Comment</button>
                <button id="hide" type="button" class="btn btn-light">Hide</button>
            </div>

            <form id='form' method="post" asp-controller="Comments" asp-action="Comment" asp-route-content="@Model.Content" asp-route-ticketId="@Model.Ticket.Id">
                <textarea asp-for="@Model.Content" class="element5" id='textarea' placeholder="Your Comment..."></textarea>
                <input id="element2" type="submit" class="btn btn-primary" value="Send">
            </form>

        </div>
        <hr />     
    </div>
</body>

<script src="~/js/hideShowComment.js" asp-append-version="true"></script>

Web/ZENBEAR.Web/Views/Tickets/MyTicketsDetails.cshtml
@model ZENBEAR.Web.ViewModels.Tickets.MyTicketDetailsViewModel
@using ZENBEAR.Data.Models.Enums

<head>
    <script src="https://kit.fontawesome.com/a199d1b466.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="~/css/finishbutton.css">
    <link rel="stylesheet" href="~/css/comments.css">
    <link rel="stylesheet" href="~/css/myTicketsDetails.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta2/css/all.min.css" integrity="sha512-YWzhKL2whUzgiheMoBFwW8CKV4qpHQAEuvilg9FAn5VJUDwKZZxkJNuGM4XkWuk94WCrrwslk8yWNGmY1EduTA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <style>
        body {
            background-image: linear-gradient(135deg, tomato, rebeccapurple);
        }
    </style>
</head>

<style>
    body {
        background-image: linear-gradient(135deg, tomato, rebeccapurple);
    }
</style>

<body>
    <div id="sides">
        <div class="tab">
            <button id="backBtn" class="buttonLeft" onclick="history.back(-1)">&#8592; Back</button>
            <p id="element">&#9889; @Model.Ticket.IssueType Issue</p>
            <p id="element">&#9806; TI-@Model.Ticket.Id</p>
        </div>
        <hr />
        <div id="sides">
            <div id="left">
                <i class="fa-light fa-ballot-check"></i>
                <h4 id="element2"><i class="fa-solid fa-envelope-open-text"></i> @Model.Ticket.Summary</h4>
                <p id="element1">Priority</p>
                <p id="element1" style="color:@(Model.Ticket.Priority == Priority.Urgent.ToString() ? "red" : "green");">&#10071;@Model.Ticket.Priority</p>
                <div id="element2">
                    <p>Attachments</p>
                    @if (Model.Ticket.Attachments != null)
                    {
                        @foreach (var item in Model.Ticket.Attachments)
                        {
                            var fileName = "/attachments/tickets/" + @item.Id + "." + @item.Extension;
                            <i class="fa-solid fa-paperclip"></i><a href="@fileName" download>Download </a>
                        }
                    }
                </div>
                <div id="element2">
                    <i class="fa-regular fa-keyboard"></i>
                    <textarea asp-for="Ticket.Description" class="form-control" rows="7"></textarea>
                    <span asp-validation-for="Ticket.Description" class="text-danger"></span>
                </div>

            </div>

            <div id="right">
                <h4 id="details">Details</h4>
                <hr />
                <table class="table-fill">
                    <tbody class="table-hover">
                        <tr>
                            <td class="text-left">Assignee</td>
                            <td class="text-left">@Model.Ticket.Assignee</td>
                        </tr>
                        <tr>
                            <td class="text-left">Reporter</td>
                            <td class="text-left">@Model.Ticket.Reporter.FullName</td>
                        </tr>
                        <tr>
                            <td class="text-left">Telephone</td>
                            @if (Model.Ticket.PhoneNumber != null)
                            {
                                <td class="text-left">@Model.Ticket.PhoneNumber</td>
                            }
                            else
                            {
                                <td class="text-left">None</td>
                            }
                        </tr>
                        <tr>
                            <td class="text-left">Email</td>
                            <td class="text-left">@Model.Ticket.Reporter.Email</td>
                        </tr>
                        <tr>
                            <td class="text-left">Department</td>
                            <td class="text-left">@Model.Ticket.Reporter.Department</td>
                        </tr>
                        <tr>
                            <td class="text-left">Jobtitle</td>
                            <td class="text-left">@Model.Ticket.Reporter.Jobtitle</td>
                        </tr>
                    </tbody>
                </table>
            </div>
            <input type="hidden" asp-for="Ticket.Id" />
            <h5 id="commentHeding">Comments</h5>
            @if (Model.Ticket.Comments != null)
            {
                @foreach (var comment in Model.Ticket.Comments)
                {
                    <div id="comment" class="comments-container">
                        <ul id="comments-list" class="comments-list">
                            <li>
                                <div class="comment-main-level">
                                    <div class="comment-box">
                                        <div class="comment-head">
                                            <h6 class="comment-name by-author">@comment.AddByUser</h6>
                                            <span>@comment.CreatedOn.ToString("dd/MM/yyyy HH:mm")</span>
                                            <i class="fa fa-reply"></i>
                                            <i class="fa fa-heart"></i>
                                        </div>
                                        <div class="comment-content">
                                            @comment.Content
                                        </div>
                                    </div>
                                </div>
                            </li>
                        </ul>
                    </div>
                }
            }
            <div id='buttons'>
                <button id="show" style="margin-left: 38px; margin-top: 20px;" type="button" class="btn btn-info">Press for Comment</button>
                <button id="hide" type="button" class="btn btn-light">Hide</button>
            </div>

            <form id='form' method="post" asp-controller="Comments" asp-action="Comment" asp-route-content="@Model.Content" asp-route-ticketId="@Model.Ticket.Id">
                <textarea asp-for="@Model.Content" class="element5" id='textarea' placeholder="Your Comment..."></textarea>
                <input id="element2" type="submit" class="btn btn-primary" value="Send">
            </form>

        </div>
        <hr />

    </div>
</body>

<script src="~/js/hideShowComment.js" asp-append-version="true"></script>